### ISSUE TITLE
feature: Add plugin to VM datasource for Grafana operator

### ISSUE THREAD

**Issue by kobin23** [VictoriaMetrics/helm-charts#2168]
**Chart name and version, where you feel a lack of requested feature**
chart: victoria-metrics-k8s-stack-chart
version: v0.45.0

**Is your feature request related to a problem? Please describe.**
Yes. When deploying the VictoriaMetrics Kubernetes stack using the Helm chart, the `GrafanaDatasource` Custom Resource created for VictoriaMetrics does not include plugin metadata (such as marking `victoriametrics-metrics-datasource` as a required plugin)

**Describe the solution you'd like**
I’d like the Helm chart to optionally (or by default) add the appropriate `plugins` field to the generated `GrafanaDatasource` CR

**Describe alternatives you've considered**
- Manually editing the `GrafanaDatasource` after deployment.
- Creating a separate `GrafanaDatasource` manifest with the plugin requirement defined.
- Using a custom overlay or post-render patch in Helm to inject the plugin information.
All of these are more error-prone and reduce the value of an automated Helm deployment.

**Additional context**
Here’s an example of the missing field:
```
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: victoria-metrics-datasource
spec:
  datasources:
    - name: VictoriaMetrics (DS)
       type: victoriametrics-metrics-datasource
       access: proxy
       url: http://vmsingle:8428
       isDefault: true
  # MISSING:
  plugins:
    - victoriametrics-metrics-datasource
```

**Comment by AndrewChubatiuk** [comment]
fixed in 0.45.1

**Comment by kobin23** [comment]
Hello!
Still missing plugins section in GrafanaDatasource on latest version of chart (0.47.1)
May be I'm doing something wrong?

Part of my values.yaml
```
defaultDatasources:
  grafanaOperator:
    # -- Create datasources as CRDs (requires grafana-operator to be installed)
    enabled: true
    annotations: {}
    spec:
      instanceSelector:
        matchLabels:
          dashboards: grafana
      allowCrossNamespaceImport: false
  victoriametrics:
    # -- Create per replica prometheus compatible datasource
    perReplica: false
    # -- List of prometheus compatible datasource configurations.
    # VM `url` will be added to each of them in templates.
    datasources:
      - name: VictoriaMetrics
        type: prometheus
        access: proxy
        isDefault: true
      - name: VictoriaMetrics (DS)
        isDefault: false
        access: proxy
        type: victoriametrics-metrics-datasource
        version: "0.14.0"
```

**Comment by kobin23** [comment]
@AndrewChubatiuk, would it be possible to reopen this issue?

**Comment by AndrewChubatiuk** [comment]
i cannot reproduce it, plugins section is absent for prometheus datasource, but victoriametrics datasource has it

**Comment by kobin23** [comment]
@AndrewChubatiuk 
I found the culprit: if I specify this plugin explicitly in the grafana.plugins section of values.yaml, it disappears from the GrafanaDatasource CR, but I’m not sure if this is the expected behavior or not

**Comment by AndrewChubatiuk** [comment]
fixed this in the latest release
